rails-basics-ru/crud/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tasks
  root 'home#index'

end

rails-basics-ru/crud/app/views/tasks/_form.html.erb
<%= form_with model: @task do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :creator %><br>
    <%= form.text_field :creator %>
  </div>

  <div>
    <%= form.label :performer %><br>
    <%= form.text_field :performer %>
  </div>

  <div>
    <%= form.label :completed %><br>
    <%= form.text_field :completed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rails-basics-ru/crud/app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form', task: @task%>

rails-basics-ru/crud/app/views/tasks/index.html.erb
<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th>Creator</th>
      <th>Performer</th>
      <th>Completed</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= task.creator %></td>
        <td><%= task.performer %></td>
        <td><%= task.completed %></td>
      </tr>
    <% end %>
  </tbody>
</table>

rails-basics-ru/crud/app/views/tasks/new.html.erb
<h1>NEW</h1>

<%= render 'form', task: @task%>

rails-basics-ru/crud/app/views/tasks/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @task.creator %>
</p>

<p>
  <strong>Performer:</strong>
  <%= @task.performer %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed ? 'Yes' : 'No' %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>
<%= link_to 'Delete', task_path(@task), method: :delete, data: { confirm: "Вы точно хотите удалить задачу ?"} %>